### ISSUE TITLE
runtimeError: Too many retries

### ISSUE THREAD

**Issue by captcharleyhalo** [obstruse/ThermalCamera#4]
Hello! I've been trying to make your project work for some time now, and I'm really close to having it work. 
However, when I try to run : ThermalCamera/Python/heat.py
I get this error :
pygame 2.1.3 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
MLX addr detected on I2C, Serial # ['0xb2b', '0xcb26', '0x189']
Traceback (most recent call last):
  File "/home/captcharleyhalo/ThermalCamera/python/heat.py", line 325, in <module>
    mlx.getFrame(temps)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_mlx90640.py", line 132, in getFrame
    status = self._GetFrameData(mlx90640Frame)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_mlx90640.py", line 161, in _GetFrameData
    raise RuntimeError("Too many retries")
RuntimeError: Too many retries

Would you know how to fix this? It's not the mlx90640 because its worked with other codes on itself, however the camera i ordered it plugged by usb... do i need to change its video input or something?

Thank you!

**Comment by obstruse** [comment]
It's  the RefreshRate, 
line #59: **mlx.refresh_rate = adafruit_mlx90640.RefreshRate.REFRESH_32_HZ**

I forgot to add to the README the part about changing the I2C freq.  Add '**i2c_arm_baudrate=1000000**' to the '**dtparam=i2c_arm**' line in /boot/config.txt:

### 1MHz for thermal camera
dtparam=i2c_arm=on,i2c_arm_baudrate=1000000

...and reboot; should fix it.  If it doesn't, you may need to reduce the refresh rate.  Let me know how it goes, I'll update the README

**Comment by captcharleyhalo** [comment]
Hello, Thank you this solved the issue.

But now I'm getting this error: 
pygame 2.1.3 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
MLX addr detected on I2C, Serial # ['0xb2b', '0xcb26', '0x189']
Traceback (most recent call last):
  File "/home/captcharleyhalo/ThermalCamera/python/heat.py", line 351, in <module>
    pygame.transform.threshold(overlay,camImage,(0,0,0),(40,40,40),(1,1,1),1)
TypeError: surf and dest_surf not the same size

It's late and I cant work on the code right now, hopping you can solve this.

Thank you very much

**Comment by obstruse** [comment]
The camera isn't giving you the resolution that you requested.
Simple solution is to use the actual camera resolution as the (width,height).  Add this after **cam.start()** line #71:

cam.start()
**(width, height) = cam.get_size()**
**print(width,height)**

To find the resolutions that your camera supports:

```
sudo apt install v4l-utils
v4l2-ctl -d /dev/video0 --list-formats-ext | grep -v Interval
```
The config.ini uses a low resolution for the camera (320,240) to get a reasonable framerate output.  Plus, the heat resolution is only (32,24)

**Comment by obstruse** [comment]
The camera isn't giving you the resolution that you requested.
Simple solution is to use the actual camera resolution as the (width,height).  Add this after **cam.start()** line #71:

cam.start()
**(width, height) = cam.get_size()**
**print(width,height)**

To find the resolutions that your camera supports:

```
sudo apt install v4l-utils
v4l2-ctl -d /dev/video0 --list-formats-ext | grep -v Interval
```
The config.ini uses a low resolution for the camera (320,240) to get a reasonable framerate output.  Plus, the heat resolution is only (32,24)

**Comment by captcharleyhalo** [comment]
The project works! 
But now I am wondering how I could edit your project to add extra features, You have helped me enough and I am good to work on my own. But if you could help me understand the code or at least where to add the lines I need, that would be great. 

I would like to add a feature where it actually tells you the temperature wherever you click on the image. I will refer another code that uses mlx90640 and that has this feature, but I don't know where or how to add it.

**Comment by captcharleyhalo** [comment]
could it be a code like this?


def get_temp_at_pos(x,y):
    # convert mouse position to thermal camera coordinates
    cx = int((x / lcdRect.width) * width)
    cy = int((y / lcdRect.height) * height)
    # get temperature at camera coordinates
    temp = mlx.get_temperature_data()[cy*width+cx]
    # convert temperature to Fahrenheit
    temp_f = temp * 9/5 + 32
    return temp_f

(while)
for event in pygame.event.get():
    if event.type == MOUSEMOTION:
        # get temperature at mouse position
        temp = get_temp_at_pos(*event.pos)
        # display temperature in console
        print(f"Temperature at ({event.pos}): {temp:.2f} °F")

**Comment by captcharleyhalo** [comment]
I'm also getting errors of it retrying too many times, could it be because both cameras arent completely 100% aligned? I'm working on a 3d print to keep them together, but in the mean time I'm resorting to a makeshift setup. Does the code recognize if the images are too far apart?

**Comment by captcharleyhalo** [comment]
> The project works! But now I am wondering how I could edit your project to add extra features, You have helped me enough and I am good to work on my own. But if you could help me understand the code or at least where to add the lines I need, that would be great.
> 
> I would like to add a feature where it actually tells you the temperature wherever you click on the image. I will refer another code that uses mlx90640 and that has this feature, but I don't know where or how to add it.

The reason I want an actual value for the temperature is because I'd like to send a notification to an atmega328p to let it know if a temperature is too hot or too cold. I'm not a python expert so any help you offer will be very nice!

Thank you

**Comment by obstruse** [comment]
Great!  So, what was the resolution that your camera provided?

I think it would be difficult to get the temperature from the mouse position because of the scaling and offsets used in ThermalCamera; it would need to be modified so that the heat image is always full-scale and not offset.  What is mlx.get_temperature_data()?  Is that from a different MLX library?  

The retry errors are probably the result of the MLX refresh rate being too high. Try: mlx.refresh_rate = adafruit_mlx90640.RefreshRate.REFRESH_16_HZ.  

The two cameras will never be completely 100% aligned, that's why the arrow keys provide adjustment.  3D print sounds nice; will it have some kind of screw adjustments to adjust camera pointing? 

So, why do you need an atmega328p?  There's plenty of GPIOs on the RPi.

**Comment by captcharleyhalo** [comment]
I am doing a project for school where I have to use two different computers (Raspberry with arduino/atmega etc..)

And sorry the code I provided was wrong and wouldn't make sense. 

My idea is to make an infrared camera that can detect if the human body has fallen into hypothermia, so it will alert the person to get warmer (or wake them up during the night if it happens while they sleep).

**Comment by captcharleyhalo** [comment]
And to be honest I only put this line: 
 cam.start()
(width, height) = cam.get_size()
print(width,height)
And it started working. I dont quite understand how to use : v4l2-ctl -d /dev/video0 --list-formats-ext | grep -v Interval
I'm abit of a noob sorry

**Comment by obstruse** [comment]
The **print(width,height)** should have printed out the resolution just below the **MLX addr detected on I2C, Serial # ['0xb2b', '0xcb26', '0x189']** line.  I sort of assumed that all USB cams could do the low resolutions.  Would be interesting to see what you got.

**v4l2-ctl -d /dev/video0 --list-formats-ext | grep -v Interval**  is a shell command, just type it at the shell prompt.  Also the **sudo apt install v4l-utils** to install the v4l2-ctl program.

Not saying the code was wrong, just that ThermalCamera moves things around with the scaling and offsets.  For example, the first temperature in the heat array isn't necessarily displayed at the first pixel location on the screen.

Maybe you don't need the visual camera?  Just scan through the temps:  a temperature >90F == found a warm body, 80 - 90F == cold body, < 80F == too late...  Seems like it would work if it was pointed at their face... but if they rolled-over or pulled the blankets up, you'd get a false reading.

I found a device that measures skin temperature:  https://www.whoop.com/thelocker/what-is-skin-temperature-and-why-should-you-monitor-it/  You could do something like that with an ESP8266 + temperature sensor + LiPo battery, running a web server.  Strap it on your arm.  Use the RPi to send HTTP requests to the ESP8266 to monitor temperature...

**Comment by captcharleyhalo** [comment]
I ordered the visual camera you had linked, the only difference it has stabilization. these are the results from both my cameras: 
Type: Video Capture

	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 2592x1944
		Size: Discrete 2048x1536
		Size: Discrete 1920x1080
		Size: Discrete 1600x1200
		Size: Discrete 1280x960
		Size: Discrete 1280x720
		Size: Discrete 800x600
		Size: Discrete 640x480
		Size: Discrete 2592x1944
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 2592x1944
		Size: Discrete 2048x1536
		Size: Discrete 1920x1080
		Size: Discrete 1600x1200
		Size: Discrete 1280x960
		Size: Discrete 1280x720
		Size: Discrete 800x600
		Size: Discrete 640x480
		Size: Discrete 2592x1944

I don't really understand what this tells me.

**Comment by captcharleyhalo** [comment]
I also changed it to 16Hz and I'm still getting the error.

**Comment by captcharleyhalo** [comment]
When I get the error it sound like something is clicking in real life?? I don't understand.

**Comment by obstruse** [comment]
The output shows that the lowest resolution supported by your camera is 640x480.  That's fine, it'll just run slower since it's processing more data.

Wonder what changed between yesterday's "project works" and today's return of runtimeError.  I assume it's showing the same MLX error messages as before?  With the I2C freq set to 1,000,000, keep lowering the refresh rate until the error goes away.  8Hz, 4Hz, etc.  By the way, what kind of RPi are you using?

The program starts in heat+edge detect mode.  If it's crashing before you can get to the menu to change the mode, you can edit the heatDisplay variable (line #190) to change the starting mode:
**heatDisplay = 0**   # display camera only
**heatDisplay = 3**   # display heat only
...to check each device individually

Don't know about the clicking.  It's coming from the USB camera?

**Comment by captcharleyhalo** [comment]
Ok so I changed the freq down to 800k / 16Hz, and seems to run smoother but the infrared quality is abit worse. The error seems random. (Raspberry pi 4). 
Btw is there anywhere in the code where I can get a value of the pixels. Like it doesn't need to be with cursor, I just want to see the numbers for every pixel. 
+
How can I change the buttons/Add buttons? like how is it a rectangle placed on the top left of the screen? I would like to add more buttons with different uses.

Also here's the error (I cant copy it all): 
e>
    mlx.getFrame(temps)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_mlx90640.py", line 132, in getFrame
    status = self._GetFrameData(mlx90640Frame)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_mlx90640.py", line 146, in _GetFrameData
    self._I2CReadWords(0x8000, statusRegister)
  File "/usr/local/lib/python3.9/dist-packages/adafruit_mlx90640.py", line 838, in _I2CReadWords
    i2c.write_then_readinto(
  File "/usr/local/lib/python3.9/dist-packages/adafruit_bus_device/i2c_device.py", line 141, in write_then_readinto
    self.i2c.writeto_then_readfrom(
  File "/usr/local/lib/python3.9/dist-packages/busio.py", line 192, in writeto_then_readfrom
    return self._i2c.writeto_then_readfrom(
  File "/usr/local/lib/python3.9/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 90, in writeto_then_readfrom
    readin = self._i2c_bus.read_i2c_block_data(
  File "/usr/local/lib/python3.9/dist-packages/Adafruit_PureIO/smbus.py", line 281, in read_i2c_block_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 5] Input/output error

**Comment by captcharleyhalo** [comment]
And also did I understand right that the arrow keys adjust the two pictures? Because that's really cool if you implemented that already. (I would like to make buttons on the screen to adjust the two pictures)

**Comment by obstruse** [comment]
Well, that's a different error.  Best I can find from googling suggests that 'OSError: [Errno 5] Input/output error' might relate to bad wiring, so make sure all the connections are tight.
 
The other thing to check is the power supply.  I'm using a 2 Amp USB-A power supply with a USB-A/USB-C cable connecting the RPi4. Works fine. I swapped the cable with a USB-A cable and a USB-A/USB-C adapter... Pi boots OK, but running heat.py gives the "Too many retries" error.  Not the OSError #5, but still...
 
To check if that's happening, run this command:
 
` grep -ai voltage /var/log/syslog` 

If you see this:

```
Mar  4 11:49:00 rpi4 kernel: [  140.003915] Under-voltage detected! (0x00050005)
Mar  4 11:49:04 rpi4 kernel: [  144.164137] Voltage normalised (0x00000000)
```

...you're got a problem.


The temperatures are in the temps array:

 `mlx.getFrame(temps)`
 
 
I use the defined function **menuButton( menuText, menuCenter, menuSize )** to draw the buttons on the menu surface.  It returns a rectangle object:

 `menuMaxPlus = menuButton('+',(230,30),(60,60) )`

...that is used to collide with the mouse position:

   ```
 pos = pygame.mouse.get_pos()
    if menuMaxPlus.collidepoint(pos):
        MAXTEMP+=1
            if MAXTEMP > 80 :
                MAXTEMP = 80
```

Yes, the arrow keys adjust the offset between the two images.  I used a totally unnecessary **UserEvent:**

 ```
# event to calculate offsets (playing with events...)
 OFFSETS = pygame.event.Event(pygame.USEREVENT)
```
...because I thought it was interesting:
 
```
	if (event.key == K_RIGHT) :
            offsetX += 1
            pygame.event.post(OFFSETS)
```
```
        if (event == OFFSETS) :
           # keep the offset scaled heat image within screen, move camera if necessary
```
So why not just create a function to re-calculate the offsets?  Yeah... but this way uses UserEvents!

**Comment by captcharleyhalo** [comment]
When I get back to school, I'll make a more permanent casing for the cameras, because I think the wiring might be affecting the pi. This being said, the capture mode doesn't work, anytime I press on capture it just gives me this error:

Also when I try to do : ThermalCamera/python/heat.py.save 
I get: 
Traceback (most recent call last):
  File "/home/captcharleyhalo/ThermalCamera/python/heat.py", line 385, in <module>
    pygame.image.save(lcd, fileName)
pygame.error: Couldn't open /home/pi/Pictures/heat20230304-221318.jpg
 
File "/home/captcharleyhalo/ThermalCamera/python/heat.py.save", line 232
    if menuMaxPlus.collidepoint(p                                    		MAXTEMP+=1
                                                                       ^
SyntaxError: invalid syntax


And also I don' really know what to do with mlx.getFrame(temps)
How do I access it?

**Comment by captcharleyhalo** [comment]
Also when I try to save the arrow movement I get this error: 
Traceback (most recent call last):
  File "/home/captcharleyhalo/ThermalCamera/python/heat.py", line 283, in <module>
    config.set('ThermalCamera', 'offsetX',str(offsetX))
  File "/usr/lib/python3.9/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'ThermalCamera'


Do i need the create that ?

**Comment by obstruse** [comment]
I guess I'm lazy:  don't think I've every bothered to create a username on an RPi.  So yeah, you'll need to change 
`fileName = "/home/pi/Pictures/heat%s.jpg" % time.strftime("%Y%m%d-%H%M%S", time.localtime())`
...to the filename you want to use.

The next syntax error is weird:
`if menuMaxPlus.collidepoint(p MAXTEMP+=1`
Looks like there's some bytes missing between the '**(p**' and '**MAXTEMP**', like the file is damaged or something. Run the command:
`git diff heat.py`
...to see what's changed.  (assuming you're using git...)

The line:
`mlx.getFrame(temps)`
...gets the data from the MLX device, calculates the temperature in C, and places it into the array **temps**.  It's a python array, so you can iterate through it or whatever.  https://adafruit.github.io/Adafruit_MLX90640/html/class_adafruit___m_l_x90640.html

Your last error shouldn't occur since config.ini is located in same directory as heat.py and is created when you cloned the repository (assuming you're using git... Oh, hmm).  So why aren't you using git?  It's GitHub after all...

**Comment by captcharleyhalo** [comment]
I tried making the file /home/pi/Pictures
And changed the path in the code to /home/pi/Pictures like this : 
if imageCapture :
                imageCapture = False
                fileName = "/home/pi/Pictures/" % time.strftime("%Y%m%d-%H%M%S">
                pygame.image.save(lcd, fileName)

But I get this error:

 File "/home/captcharleyhalo/ThermalCamera/python/heat.py", line 384, in <module>
    fileName = "/home/pi/Pictures/" % time.strftime("%Y%m%d-%H%M%S", time.localtime())
TypeError: not all arguments converted during string formatting
.


Also I've followed tutorial step by step, so I don't understand when else I'm supposed to use git


And am I supposed to add code to get the temps from mlx.getframe? Or is that what you mean by using git?

**Comment by obstruse** [comment]
The problem is that you seem to be logged in as **captcharleyhalo**, which means that you don't have write access to the **/home/pi/Pictures** directory:

```
pi@rpi4:~ $ ls -ld /home/pi/Pictures/
drwxr-xr-x 2 pi pi 36864 Jun 23  2022 /home/pi/Pictures/
```

You need to change that to a location you have write access to (e.g. **/home/captcharleyhalo** )

The '%' is a python formatting character; you shouldn't have removed the '%s'.  Here's a web page:  https://www.learnpython.org/en/String_Formatting

I was sort of kidding about git. I guess you probably ran heat.py from the /home/captcharleyhalo directory, so it was looking for config.ini there instead of in /home/captcharleyhalo/ThermalCamera/python.  Yeah, I should fix that too.  So just cd to **/home/captcharleyhalo/ThermalCamera/python** and run **./heat.py** from there

Line #325 of heat.py is **mlx.getFrame(temps)**; that's how it gets the temperatures from the sensor.  The temperatures are just sitting there, you can do whatever you want with them.

**Comment by captcharleyhalo** [comment]
I couldn't fix the error for screen capture so I tried to reinstall the git project but I've come to this error:Install packages...
...update package lists
All packages are up to date.
...pygame
Package python-pygame is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pygame' has no installation candidate 

I've tried so many solutions but nothing works. Pls help

**Comment by obstruse** [comment]
That's weird.  The install script hides some of the messages, try running the pygame install directly from the command line, see if it prints more info:

`sudo apt install -y python-pygame`

On the other hand it's probably still installed anyway

**Comment by captcharleyhalo** [comment]
No matter what. I always get : Building dependency tree... Done
Reading state information... Done
Package python-pygame is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pygame' has no installation candidate
 

I had this issue before, but I got to make it work. I don't remember what I did or what tutorial i followed. I tried going into my history, but can't find anything.

**Comment by captcharleyhalo** [comment]
https://stackoverflow.com/questions/61277774/pip-is-not-installing-pygame-and-is-giving-error
This website says i should run : 
$ sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev   libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev

But i get this error : 
sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev   libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev~
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-numpy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-numpy' has no installation candidate
E: Unable to locate package libavcodec-dev~


But I also cant find anything that will fix python-numpy

**Comment by obstruse** [comment]
_Note, selecting 'python-dev-is-python2' instead of 'python-dev'_

Looks like it's trying to install python2.  That's not good, it's pretty much not supported any more.  What do you get for the python version:

`python -V`

and do the usual:
```
sudo apt update
sudo apt upgrade
```

**Comment by captcharleyhalo** [comment]
python -V
Python 2.7.18
sudo apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                          
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                  
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease                 
Reading package lists... Done                              
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
captcharleyhalo@raspberrypi:~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by obstruse** [comment]
Yeah, python 2 isn't going to work.  Usually that's controlled by update-alternatives, as in

```
pi@rpi4:~ $ sudo update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                       Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.7          3         auto mode
* 1            /usr/bin/python3.7          3         manual mode
  2            /usr/local/bin/python3.11   1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 

```

**Comment by captcharleyhalo** [comment]
i get : update-alternatives: error: no alternatives for python

**Comment by captcharleyhalo** [comment]
sudo update-alternatives --config python
There is only one alternative in link group python (providing /usr/bin/python): /usr/bin/python2.7
Nothing to configure.

but if i do python -V i get
Python 3.7.0

**Comment by captcharleyhalo** [comment]
Is there a way to completely remove everything that has been downloaded for your project and to reinstall it? 
To my knowledge pygame is downloaded and the program is just having a bug?
Infact i know pygame is downloaded because I can play pygames

Are you running a pi4 for your project?

**Comment by captcharleyhalo** [comment]
Plus this isn't a random error, I got a new sd card and started from scratch, and I'm getting the same error...

**Comment by captcharleyhalo** [comment]
If it's easier for you, we can join a zoom or whatever you use for methods of communication so we can resolve this faster

**Comment by captcharleyhalo** [comment]
The issue keeps persisting all across python tools, like python-smbus, python-pygames python-i2c-tools

**Comment by obstruse** [comment]
I guess I lost track:  Which issue exactly?  What's the error message?

I just pushed a new version of ThermalCamera to github, which I think addresses some of your issues

**Comment by captcharleyhalo** [comment]
The main issue is when I do 
sudo ThermalCamera/install/installCamera.sh

I get:

Install packages...
...update package lists
All packages are up to date.
...pygame
Package python-pygame is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pygame' has no installation candidate


I've seriously been loosing my mind over this issue.

What I was trying to say is that, this error or something not having its *installation candidate* has been happening for a few other projects that use mlx906040.

like python-smbus

**Comment by captcharleyhalo** [comment]
do i need to delete git clone https://github.com/obstruse/ThermalCamera.git
(the one i already downloaded)
So i can download your new one?

**Comment by captcharleyhalo** [comment]
I did sudo rm -R ThermalCamera/

And redownloaded 

But still get the error

**Comment by captcharleyhalo** [comment]
This is really weird, even tho i cant do sudo ThermalCamera/install/...
I can still go into Thermalcamera/python/heat.py
but i get this error : 
Traceback (most recent call last):
  File "/home/pi/ThermalCamera/python/./heat.py", line 7, in <module>
    import adafruit_mlx90640
ModuleNotFoundError: No module named 'adafruit_mlx90640'

**Comment by captcharleyhalo** [comment]
ok fixed it with pip3 install adafruit-circuitpython-mlx90640
but now i get this error
<frozen importlib._bootstrap>:228: RuntimeWarning: Your system is neon capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected
Traceback (most recent call last):
  File "/home/pi/ThermalCamera/python/./heat.py", line 44, in <module>
    i2c = busio.I2C(board.SCL, board.SDA)
  File "/usr/local/lib/python3.9/dist-packages/busio.py", line 35, in __init__
    self.init(scl, sda, frequency)
  File "/usr/local/lib/python3.9/dist-packages/busio.py", line 129, in init
    raise ValueError(
ValueError: No Hardware I2C on (scl,sda)=(3, 2)
Valid I2C ports: ((1, 3, 2), (0, 1, 0), (10, 45, 44))

**Comment by captcharleyhalo** [comment]
Ok fixed the i2c error but now i get this error: 

/home/pi/ThermalCamera/python/./heat.py:56: RuntimeWarning: use font: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
(ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory)
  font = pygame.font.Font(None, 30)
Traceback (most recent call last):
  File "/home/pi/ThermalCamera/python/./heat.py", line 56, in <module>
    font = pygame.font.Font(None, 30)
  File "/home/pi/.local/lib/python3.9/site-packages/pygame/__init__.py", line 70, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: font module not available (ImportError: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory)

**Comment by captcharleyhalo** [comment]
i got it working!

**Comment by captcharleyhalo** [comment]
The  image it gives is a square that i cant change, how can i make it a full screen square.
Also the resolution looks somehow worse

**Comment by obstruse** [comment]
So, what was the final solution?

Yeah, in the old version the camera resolution and the screen resolution had to be the same.  In this version, I separated the two, so you can specify any screen resolution you want, and it will find a matching camera resolution to use.  It's defaulting to 320x240; edit config.ini for the size you want.  It can be anything, but the width:height ratio should be 4:3 or it will be distorted.

**Comment by captcharleyhalo** [comment]
so basically i only had to do git clone https://github.com/obstruse/ThermalCamera.git

and then do cd ThermalCamera/python
then do ./heat.py

no need to do sudo ThermalCamera/install/...


This being said, the screen shot function still doesn't work.

**Comment by obstruse** [comment]
What was the error?

**Comment by captcharleyhalo** [comment]
No error, the button doesn't even click

**Comment by obstruse** [comment]
"Click?" What do you mean?  It's supposed to place a JPG in your ~/Pictures directory.  It doesn't?

**Comment by captcharleyhalo** [comment]
When I click W to save the position I get this error 

configparser.NoSectionError: No section: 'ThermalCamera'

**Comment by captcharleyhalo** [comment]
The capture does work! Thats so cool.

**Comment by obstruse** [comment]
So, what do you have in ThermalCamera/python/config.ini ?

**Comment by captcharleyhalo** [comment]
[ThermalCamera]
offsetx = 0
offsety = 0
width = 320
height = 240
camfov = 35
heatfov = 40
theme = 1
videoDev = /dev/video0

**Comment by obstruse** [comment]
Looks good.  As long as that file is in the same directory as the heat.py you're executing, don't see why you'd have a problem.

**Comment by captcharleyhalo** [comment]
![IMG_6282](https://user-images.githubusercontent.com/124080186/223589354-b0a99602-7d9a-4834-b2f2-36a4b08271ac.jpg)
![IMG_6281](https://user-images.githubusercontent.com/124080186/223589379-80955177-bc62-46b0-9d04-9fa80bf6aae6.jpg)

Idk if this is going to work, but I'm sending you a picture of my setup (Idk if you care or not lol)

It's also to show how its only a square, can i change it a rectangle or something

**Comment by obstruse** [comment]
Looks good... (although I really want to rip that plastic off the screen...)

Actually it is rectangular.  You can make the display any size you want, just edit config.ini.  The heat image is 4:3 aspect ratio, and the camera image is 4:3; if you set the display size to something that isn't 4:3, when the program stretches the images to fit it will look distorted.  So 1280x960 would work without distortion, or 400x300, etc.

**Comment by captcharleyhalo** [comment]
I've been messing around with the aspect ratio but nothing makes the actual screen bigger,

And hahah the screen protector is just to make sure I dont scratch the screen for now,
I work with vnc viewer most of the time

**Comment by captcharleyhalo** [comment]
Like how do I make the image full screen, so i don't see anything around

**Comment by captcharleyhalo** [comment]
Ok nvm the line had you given me earlier :cam.start()
(width, height) = cam.get_size()
print(width,height)

Works!

I would still like to make it full screen but this makes the image alot bigger

**Comment by obstruse** [comment]
Yeah, but... I'm concerned that you've been saying that it isn't finding the config.ini file.
Could you add this after line #28: 
 ```
 os.chdir(os.path.dirname(os.path.abspath(__file__)))
 print(os.path.dirname(os.path.abspath(__file__)))
 print(os.listdir())
```
...and send me the results.

I think fullscreen makes sense on a small capacitive-touch TFT screen (320x240), but  it's a bad idea on a larger 16:9 screen

**Comment by captcharleyhalo** [comment]
I don't understand what you want me to send you, when I put it and run ./heat.py it just runs normally.

**Comment by obstruse** [comment]
Yeah, I want to see the output of the two print statements.  Trying to see why it's not finding config.ini and not picking up the width/height settings.  Also, I think you said that "w" gives an error, also suggesting that the file isn't where it's supposed to be.
Maybe `__file__`  isn't resolving correctly?  Also add this print statement to check:

`print(__file__)`

**Comment by captcharleyhalo** [comment]
Nothing prints, like I dont see anything. Would it be at the start of ./heat.py?

**Comment by obstruse** [comment]
It should look similar to this:

```
pi@rpi4:~/ThermalCamera/python $ ./heat.py 
/home/pi/ThermalCamera/python
['heat.py', 'wiringpi-latest.deb', 'i2cspeed.sh', 'camera.py', '10sec.sh', 'x.txt', 'config.ini']
MLX addr detected on I2C, Serial # ['0x1017', '0xf6f4', '0x189']
(640, 480)
```

...and the code in heat.py should look like this:

```
from configparser import ConfigParser

# change to the python directory
os.chdir(os.path.dirname(os.path.abspath(__file__)))
print(os.path.dirname(os.path.abspath(__file__)))
print(os.listdir())

# read config
config = ConfigParser()
config.read('config.ini')

```

**Comment by captcharleyhalo** [comment]
![Capture d’écran 2023-03-08 110415](https://user-images.githubusercontent.com/124080186/223765338-fb8b37a6-6e96-46db-8885-3871ac49d95c.png)

<frozen importlib._bootstrap>:228: RuntimeWarning: Your system is neon capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected
/home/pi/ThermalCamera/python
['config.ini', 'camera.py', 'heat.py']
/home/pi/ThermalCamera/python/./heat.py
MLX addr detected on I2C, Serial # ['0xb2b', '0xcb26', '0x189']
640 480
(640, 480)
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 220 (212), X11 KeySym 0x1008FF8F (XF86WebCam).
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11

**Comment by obstruse** [comment]
That's what I expected to see (other than that RunTimeWarning and the keypress error...I guess we can ignore those for now).  Everything is where it needs to be.  The next lines will read the values from config.ini.

So if you **edit config.ini** and change the values for width and height to something like 1000 and 750, you don't see any change in the display? That doesn't make sense... Maybe you're installing stuff as '/home/pi' but you're running it from user captcharleyhalo, and the file permissions are getting in the way?  The installation was was assuming that you logged in as 'pi', and you install it in your local directory.  Looks like some of the time it was in:
"/home/captcharleyhalo/ThermalCamera/python/heat.py"
.. and now it's in 
"/home/pi/ThermalCamera/python/./heat.py"

Try it again.  But first, remove the code you added:

_Ok nvm the line had you given me earlier :cam.start()
(width, height) = cam.get_size()
print(width,height)_

**Comment by captcharleyhalo** [comment]
It's because I restarted my SD card and made a new user called pi to simplify everything.
When I take away the line (width, height) = cam.get_size()
print(width,height)

Everything looks way worse and the resolution doesn't look like its changing

**Comment by captcharleyhalo** [comment]
Also how does edge detection work and what can we do with it?

**Comment by obstruse** [comment]
No, that doesn't make any sense.  Show me the config.ini that you're using:  /home/pi/ThermalCamera/python/config.ini

One way to debug this is to force a known error.  For instance,  set the width to this:

`width = 640x`

ConfigParser should complain at length...

**Comment by captcharleyhalo** [comment]
I put it to : 
  GNU nano 5.4                       config.ini                                 
[ThermalCamera]
offsetx = 0
offsety = 0
width = 2592
height = 1944
camfov = 35
heatfov = 40
theme = 1
videoDev = /dev/video0


Just for fun

**Comment by captcharleyhalo** [comment]
I put the width to 640 and ./heat works

**Comment by captcharleyhalo** [comment]
![IMG_6287](https://user-images.githubusercontent.com/124080186/223855507-1a3f9730-ef30-4531-ae65-95f6e6e794a7.jpg)
![IMG_6288](https://user-images.githubusercontent.com/124080186/223855533-ac72d387-39d0-471d-a9c5-6e9adcdb5695.jpg)
![IMG_6289](https://user-images.githubusercontent.com/124080186/223855822-148684cf-5c26-4cd8-a8d7-39f7185d6546.jpg)

750/1000 900/1200 and 320/240

They are all the same

**Comment by obstruse** [comment]
Ah, much better without the plastic!

Ok, so did you try it with an invalid width?  Like `width = 640x` ? Then at we could see if the program is reading the config file.

Try changing **theme**.  Set it to `theme = 3`, that should look different

Send me the config.ini file.  Maybe it's got some binary data in it?

Finally:  run this and send me the result:

```
cd ThermalCamera/python
git diff heat.py

```

**Comment by captcharleyhalo** [comment]
When I do git diff heat.py, this is what  I get :

    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       Output to a specific file


I feel like this isnt saying anything and just saying how to use diff, am i wrong?

**Comment by captcharleyhalo** [comment]
And for the theme... I don't see any difference. What should it change?

**Comment by obstruse** [comment]
The top part of the git command output got cut off: what you typed in, and what happened right after that. That's the part that will indicate the error...

- so what happened when you typed in an invalid width, e.g. `width = 640x` ?
- send the config.ini file that you're using with edits.  Maybe there's some binary or something in it
- the theme changes the colors.  If the colors didn't change then the two points above will help
- if you can git clone, git diff will work as well.  Google?

**Comment by captcharleyhalo** [comment]
[ThermalCamera]
offsetx = 0
offsety = 0
width =640x
height =480
camfov = 35
heatfov = 40
theme = 1
videoDev = /dev/video0

**Comment by captcharleyhalo** [comment]
![IMG_6301](https://user-images.githubusercontent.com/124080186/224575555-5e5a05be-4fb8-4860-a058-023139cb9396.jpg)

Image when width = 640x

**Comment by captcharleyhalo** [comment]
Picture mode 3 and 4:

![IMG_6302](https://user-images.githubusercontent.com/124080186/224575651-6020a9e2-2946-462b-ab5a-a521a96ceaec.jpg)
![IMG_6303](https://user-images.githubusercontent.com/124080186/224575654-c1b126ac-6ba4-426e-86e5-3695508d8ed3.jpg)

**Comment by captcharleyhalo** [comment]
when i do git diff heat.py it wont let me scroll up... I really dont know why, i would like to copy you the full message but it wont let me

**Comment by captcharleyhalo** [comment]
Also did you write the full python code with only using your space bar? Did you use TAB for indentation?

**Comment by captcharleyhalo** [comment]
I'm able to use the (temps ) array pretty easily! 
Thank you for all your help by the way.

**Comment by captcharleyhalo** [comment]
The other comment under your post has talked about face recognition, but with no response. Was there any continuation to that subject?

**Comment by captcharleyhalo** [comment]
And also finally, would it be possible to make an auto focus ?

**Comment by obstruse** [comment]
- send the `config.ini `file that you're using. Probably a low probability, but if there was some binary strangeness, I'd need to see the file.  Zip the file on the RPi, and attached to a message. Or, make an octal dump of the file -  Run:
`od -c config.ini`
and send the output

- So, `width = 640x` didn't generate an error? For some reason it's not opening the config file.  Try running this at the python prompt:

```
pi@rpi4:~/ThermalCamera/python $ python
Python 3.7.3 (default, Oct 31 2022, 14:04:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.sections()
[]
>>> config.read('config.ini')
['config.ini']
>>> config.sections()
['ThermalCamera']
>>> config.getint('ThermalCamera','width')
320

```
- What's that error I see in the background: **mError: Connot identify '/dev/video0': 2, no such file or directory**  When does that come up?

- git diff.  Well, if the diff output is too big to fit in your window, that says a lot.  If you're running the same file that's in the repository, the git diff would be empty.  Sure, you added a few print statements, but the changes should fit in one window I think.    If you're running **lxterminal**, you can change the scroll size under **Edit->Preferences**.  I better idea would be to redirect the git diff output to a file and attach that.

- git pull.  Evidently you need to refresh you copy of heat.py.  Rename the heat.py file and run:
`git pull`

- On the RPi I use vim as the editor, with these extensions in the .vimrc file:

```
pi@rpi4:~/ThermalCamera/python $ cd
pi@rpi4:~ $ cat ~/.vimrc

filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

syntax on

pi@rpi4:~ $ 

```
... it replaces TAB character with spaces, 4 column tabstop.  On a regular workstation, I use VSCode, which has a similar tab option

- face detection?  Nope.

- Auto focus?  I don't know, I don't have a camera that does auto focus.  It's probably a command that is sent to the camera to enable it.

**Comment by captcharleyhalo** [comment]
sudo od -c config.ini gives : 
0000000   [   T   h   e   r   m   a   l   C   a   m   e   r   a   ]  \n
0000020   o   f   f   s   e   t   x       =       0  \n   o   f   f   s
0000040   e   t   y       =       0  \n   w   i   d   t   h       =   6
0000060   4   0   x  \n   h   e   i   g   h   t       =   4   8   0  \n
0000100   c   a   m   f   o   v       =       3   5  \n   h   e   a   t
0000120   f   o   v       =       4   0  \n   t   h   e   m   e       =
0000140       4  \n   v   i   d   e   o   D   e   v       =       /   d
0000160   e   v   /   v   i   d   e   o   0  \n
0000172

**Comment by captcharleyhalo** [comment]
For the video dev error, I just had to reboot my rasp so it can detect the camera again.

Also for import configparser, it gives me this error: ImportError: No module named configparser

I tried to do pip install configparser but still doesn't work

**Comment by obstruse** [comment]
- the config.ini file. Well, the octal dump looks fine, although `theme=4 `will generate an error since there's only themes 0 - 3.  By the way: why the "sudo"?  _sudo od -c config.ini_

- OK, let me guess:  it didn't say Python 3 when you typed the command, because you're still using Python 2 as your default version.  Can you google `update-alternatives config python` and correct that?  the commands that you'll type in will look something like this (but with the correct version numbers):

```
sudo update-alternatives --config python
update-alternatives: error: no alternatives for python

sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1 
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
sudo update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path              Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python2   2         auto mode
  1            /usr/bin/python2   2         manual mode
  2            /usr/bin/python3   1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
```

...meanwhile, type **python3** instead of python:

```
pi@rpi4:~/ThermalCamera/python $ **python3**
Python 3.7.3 (default, Oct 31 2022, 14:04:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.sections()
[]
>>> config.read('config.ini')
['config.ini']
>>> config.sections()
['ThermalCamera']
>>> config.getint('ThermalCamera','width')
320
```

- **mError: Connot identify '/dev/video0': 2, no such file or directory**
Does the error happen very often? Seems odd that it would happen at all. I mentioned before about checking the power with:
 `grep -ai voltage /var/log/syslog`
 Did you do that and what was the result?
   
- git diff. Any luck with this?  Redirect the output, attach a file...

- git pull. So what happened with the git pull?

**Comment by captcharleyhalo** [comment]
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.sections()
[]
>>> config.read('config.ini')
[]
>>>  config.sections()
  File "<stdin>", line 1
    config.sections()
IndentationError: unexpected indent
>>> config.getint('ThermalCamera','width')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'ThermalCamera'
>>>

**Comment by captcharleyhalo** [comment]
Also getting this error at the start when i run ./heat.py
<frozen importlib._bootstrap>:228: RuntimeWarning: Your system is neon capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected
/home/pi/ThermalCamera/python
['config.ini', 'camera.py', 'heat.py']
/home/pi/ThermalCamera/python/./heat.py
MLX addr detected on I2C, Serial # ['0xb2b', '0xcb26', '0x189']
^CTraceback (most recent call last):
  File "/home/pi/ThermalCamera/python/./heat.py", line 79, in <module>
    cam.start()

**Comment by captcharleyhalo** [comment]
And using sudo cause if i dont it says i dont have permission

**Comment by captcharleyhalo** [comment]
when i do grep -ai voltage /var/log/syslog, it doesn't do anything just enters it

**Comment by captcharleyhalo** [comment]
Also, my friend will be lending me a jetson nano, so if everything works well I should be able to bring these two cameras to a crazy frame rate.

**Comment by obstruse** [comment]
- the config.ini file. **AH HAH!!** _**And using sudo cause if i dont it says i dont have permission**_.  The way this works is that you install ThermalCamera in your own account, so that you have full permissions on everything:

```
pi@rpi4:~/ThermalCamera/python $ whoami
pi
pi@rpi4:~/ThermalCamera/python $ ls -l
total 96
-rwxr-xr-x 1 pi pi  1072 Mar  7 15:23 camera.py
-rw-r--r-- 1 pi pi   123 Mar 13 22:11 config.ini
-rwxr-xr-x 1 pi pi 16577 Mar 11 17:38 heat.py
pi@rpi4:~/ThermalCamera/python $ 
```
If you want to logon as captcharleyhalo, then that's where you install the program.  Don't use sudo, never use sudo unless you're specifically updating system files. Don't do that!  Where else were you using sudo?

- How are you coming with the update-alternatives configuration? (Note: sudo because it's updating the system python links)

```
sudo update-alternatives --config python
update-alternatives: error: no alternatives for python
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1 
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
sudo update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path              Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python2   2         auto mode
  1            /usr/bin/python2   2         manual mode
  2            /usr/bin/python3   1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
```

- You sent some output of this, but it looks strange.  The idea is to run the python commands interactively, without the complications from the rest of the program.  So, type python3 and it will prompt with '>>>'.  Type in a command, etc. (Note: no sudo)

```
pi@rpi4:~/ThermalCamera/python $ python3
Python 3.7.3 (default, Oct 31 2022, 14:04:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.sections()
[]
>>> config.read('config.ini')
['config.ini']
>>> config.sections()
['ThermalCamera']
>>> config.getint('ThermalCamera','width')
320
```

- mError: Connot identify '/dev/video0': 2, no such file or directory
OK, so no voltage problems. Does the error happen very often? Seems odd that it would happen at all.

- git diff. Any luck with this?  Redirect the output, attach a file...

- git pull. So what happened with the git pull?  you might need a different git command...

**Comment by captcharleyhalo** [comment]
I understand what you mean by not using sudo. But, I'm not logged in as captcharleyhalo anymore. I restarted my sd card and started from scratch. I'm now logged in as pi. 

pi@raspberrypi:~/ThermalCamera/python $ whoami
pi
pi@raspberrypi:~/ThermalCamera/python $ ls -l
total 28
-rwxr-xr-x 1 root root  1072 Mar  7 13:28 camera.py
-rwxr-x--- 1 root root   122 Mar 12 17:46 config.ini
-rwxr-xr-x 1 root root 16750 Mar 12 21:04 heat.py
pi@raspberrypi:~/ThermalCamera/python $ 


Do i need to make another user under this user and give it the chmod permission?

**Comment by captcharleyhalo** [comment]
pi@raspberrypi:~ $ sudo update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path              Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python2   2         auto mode
  1            /usr/bin/python2   2         manual mode
  2            /usr/bin/python3   1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/bin/python3 to provide /usr/bin/python (python) in manual mode

**Comment by captcharleyhalo** [comment]
Still getting this, even if i do python3:

>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.sections()
[]
>>> config.read('config.ini')
[]
>>> config.sections()
[]
>>> config.getint('ThermalCamera','width')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/configparser.py", line 818, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'ThermalCamera'
>>>

**Comment by captcharleyhalo** [comment]
git diff and git pull really dont do much.

**Comment by obstruse** [comment]
- the config.ini file and sudo. Notice how my output:

```
pi@rpi4:~/ThermalCamera/python $ whoami
pi
pi@rpi4:~/ThermalCamera/python $ ls -l
total 96
-rwxr-xr-x 1 pi pi  1072 Mar  7 15:23 camera.py
-rw-r--r-- 1 pi pi   123 Mar 13 22:11 config.ini
-rwxr-xr-x 1 pi pi 16577 Mar 11 17:38 heat.py
pi@rpi4:~/ThermalCamera/python $ 
```
...looks different than your output:

```
pi@raspberrypi:/ThermalCamera/python $ whoami
pi
pi@raspberrypi:/ThermalCamera/python $ ls -l
total 28
-rwxr-xr-x 1 root root 1072 Mar 7 13:28 camera.py
-rwxr-x--- 1 root root 122 Mar 12 17:46 config.ini
-rwxr-xr-x 1 root root 16750 Mar 12 21:04 heat.py
pi@raspberrypi:~/ThermalCamera/python $
```

**'root**' owns the files in the ThermalCamera directory.  In particular, look at the permissions on config;ini:

`-rwxr-x--- 1 root root 122 Mar 12 17:46 config.ini-rwxr-x---`

...that's Read,Write.eXecute for the user root, Read,eXecute for members of the root group, and **No Access for everyone else** for instance the user pi.  There's no way that the user **pi** could have created that, so evidently you did  **sudo** when you cloned the repo.  Don't do that.

No, don't make another user; no chmod'ing or chown'ing.  Get rid of the ThermalCamera directory (you'll probably need to use sudo to do that).  Log in as pi or captcharleyhalo or what ever you want.  Execute the git clone command.  You will own all the files and have full access.  I've edited the README to remove references to '/home/pi', since that seems to have caused some confusion.

- update-alternatives.  Looks good.  So now you should get this:

```
pi@rpi4:~ $ python -V
Python 3.7.3
```

- Testing configparser in python.   I guess that output looks strange because you didn't use the '<>' tags around it.  The markdown formatting on github interpreted the '>>>' as a formatting command.  If you're replying on the github webpage, you should see that option in the menu bar.

The output errors are perfectly normal since you have no access to the config.ini file you're trying to read (see above)

- mError: Connot identify '/dev/video0': 2, no such file or directory
So, not a problem?  Doesn't happen any more?

- git diff. Yeah, ideally it shouldn't display anything, since you're running the same version as is in the repository.  So that's an improvement from what you got before:

**_when i do git diff heat.py it wont let me scroll up..._**

- git pull. Also good, since you've got the current version of everything.

**Comment by captcharleyhalo** [comment]
wow! all i had to do was sudo su. then chmod 777 to config.ini heat.py and camera.py. Now it all works.

**Comment by captcharleyhalo** [comment]
Thank you for all the help. It has truly been appreciated. For the mean time I dont have any other question now that all is working.

**Comment by obstruse** [comment]
Great!  I'll close the issue
